apiVersion: flox.dev/v1alpha1
kind: FloxEnvironment
metadata:
  name: home
spec:
  manifest:
    version: 1
    install:
      direnv:
        pkg-path: direnv
      linux-builder:
        pkg-path: darwin.linux-builder
        systems:
          - aarch64-darwin
      lldpd:
        pkg-path: lldpd
    options:
      systems:
        - aarch64-darwin
        - aarch64-linux
    include:
      environments:
        - dir: /var/lib/git/nxmatic/fleet-manifests/flox/xdg # kpt-set: ${fleet-base-dir}/xdg
        - dir: /var/lib/git/nxmatic/fleet-manifests/flox/keyhole # kpt-set: ${fleet-base-dir}/keyhole
  env:
    name: home
    version: 1
