apiVersion: flox.dev/v1alpha1
kind: FloxEnvironment
metadata:
  name: xdg
spec:
  manifest:
   version: 1
   install:
     xdg-user-dirs:
       pkg-path: xdg-user-dirs
     xdg-utils:
       pkg-path: xdg-utils
     xdg-ninja:
       pkg-path: xdg-ninja
   profile:
    common: |
      set -a

      XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
      XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
      XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
      XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
      XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-$HOME/.xdg}

      set +a
   options: {}
  env:
    name: xdg
    version: 1
